/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DupesSlugRouteImport } from './routes/dupes.$slug'
import { Route as GoOfferIdRouteImport } from './routes/go.$offerId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as VsPairRouteImport } from './routes/vs.$pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DupesSlugRoute = DupesSlugRouteImport.update({
  id: '/dupes/$slug',
  path: '/dupes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoOfferIdRoute = GoOfferIdRouteImport.update({
  id: '/go/$offerId',
  path: '/go/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VsPairRoute = VsPairRouteImport.update({
  id: '/vs/$pair',
  path: '/vs/$pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dupes/$slug': typeof DupesSlugRoute
  '/go/$offerId': typeof GoOfferIdRoute
  '/p/$slug': typeof PSlugRoute
  '/vs/$pair': typeof VsPairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dupes/$slug': typeof DupesSlugRoute
  '/go/$offerId': typeof GoOfferIdRoute
  '/p/$slug': typeof PSlugRoute
  '/vs/$pair': typeof VsPairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dupes/$slug': typeof DupesSlugRoute
  '/go/$offerId': typeof GoOfferIdRoute
  '/p/$slug': typeof PSlugRoute
  '/vs/$pair': typeof VsPairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/dupes/$slug' | '/go/$offerId' | '/p/$slug' | '/vs/$pair'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/admin' | '/dupes/$slug' | '/go/$offerId' | '/p/$slug' | '/vs/$pair'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dupes/$slug'
    | '/go/$offerId'
    | '/p/$slug'
    | '/vs/$pair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DupesSlugRoute: typeof DupesSlugRoute
  GoOfferIdRoute: typeof GoOfferIdRoute
  PSlugRoute: typeof PSlugRoute
  VsPairRoute: typeof VsPairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dupes/$slug': {
      id: '/dupes/$slug'
      path: '/dupes/$slug'
      fullPath: '/dupes/$slug'
      preLoaderRoute: typeof DupesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$offerId': {
      id: '/go/$offerId'
      path: '/go/$offerId'
      fullPath: '/go/$offerId'
      preLoaderRoute: typeof GoOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$pair': {
      id: '/vs/$pair'
      path: '/vs/$pair'
      fullPath: '/vs/$pair'
      preLoaderRoute: typeof VsPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DupesSlugRoute: DupesSlugRoute,
  GoOfferIdRoute: GoOfferIdRoute,
  PSlugRoute: PSlugRoute,
  VsPairRoute: VsPairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
